name: Build Zed on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Enable long paths in Git
        run: git config --system core.longpaths true

      - name: Enable long paths in Windows registry
        shell: pwsh
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
                           -Name "LongPathsEnabled" `
                           -Value 1 `
                           -PropertyType DWORD `
                           -Force
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install dependencies
        run: |
          choco install llvm unzip curl git ninja visualstudio2019buildtools nodejs -y
      - name: Build Zed
        run: cargo build --release

      - name: Upload Zed binary
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-build
          path: target/release/zed.exe